### ISSUE TITLE
Add Jenkins JUnitAttachment plugin support

### ISSUE THREAD

**Issue by lordofthejars** [arquillian/arquillian-recorder#22]
By default Jenkins does not store the JUnit results nor any file generated by the tests. For this reason you need to set Jenkins to publish JUnit results. But sometimes like recorder does, it generates documents, images or videos of the execution. These files are not archived by default as well. The best way to do it is by adding support for JUnitAttachment plugin which is a plugin that can do this. (https://wiki.jenkins-ci.org/display/JENKINS/JUnit+Attachments+Plugin)

The best way to do it is by simply writing in the console a special tag.
So what we can do is that if `JENKINS_URL ` environment variable is set (means that test is being executed inside Jenkins) print this special tag. Of course we can add a flag to disable this as well.

**Comment by smiklosovic** [comment]
Feel free to implement this, I will be more then happy to merge this if you find it useful.

**Comment by lordofthejars** [comment]
Sure I will do it, simply I need to find the place, since I would need to create a zip file or something with the report and the images/videos.

**Comment by smiklosovic** [comment]
@MatousJobanek maybe you could look at this as well

**Comment by smiklosovic** [comment]
by the way, is not it possible to specify what files will be archived directly in a Jenkins job settings? I think that you can say - by some regexp - which resources should be archived after Jenkins job has run. If it is true, I would therefore leave the responsibility to archive some resources on Jenkins instead of implementing this functionality to the reporter itself. I think that reporter should not be aware of any underlying runtime environment at all.

**Comment by lordofthejars** [comment]
Yes there are several ways to do it, one is using the Archive plugin which does what you mention, but there are other plugins like JUnitAttachment plugin which works by sysout approach.
